### ISSUE TITLE
Unknown Issue after entering API Key

### ISSUE THREAD

**Issue by PierrunoYT** [fynnfluegge/codeqai#29]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Scripts\codeqai.exe\__main__.py", line 7, in <module>
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\codeqai\__main__.py", line 5, in main
    app.run()
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\codeqai\app.py", line 108, in run
    repo_name = repo.get_git_root(os.getcwd()).split("/")[-1]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\codeqai\repo.py", line 8, in get_git_root
    git_repo = Repo(path, search_parent_directories=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pierr\AppData\Local\Programs\Python\Python311\Lib\site-packages\git\repo\base.py", line 276, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: C:\Users\pierr

**Comment by fynnfluegge** [comment]
Hey @PierrunoYT can you check if it is solved with this [0.0.10](https://github.com/fynnfluegge/codeqai/releases/tag/0.0.10)
